apiVersion: v1
kind: Pod
metadata:
  name: pod2-1
  labels:
      type: web
      lo: dev
spec:
  containers:
    - name: container
      image: hkx2r0i/app
      ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Pod
metadata:
  name: pod2-2
  labels:
      type: web
      lo: prod
spec:
  containers:
    - name: container
      image: hkx2r0i/app
      ports:
        - containerPort: 8080